#!/bin/sh

#
# Copyright JamesZBL 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

home_path=~/.keykee
pid_file=${home_path}/.pid
boot_script=/etc/profile.d/keykee.sh
work_path=$(dirname $(readlink -f $0))
ln -s -f $work_path/keykee.sh $boot_script
ln -s -f $work_path/App /usr/bin/keykee
if [ -f $pid_file ]; then
    pid="$(cat $pid_file)"
    if ps -p $pid > /dev/null; then
        echo "An Keykee instance (PID:$pid) of old version is running, it will exit. "
        kill $pid
    fi
fi
if [ ! -d $home_path ]; then
    mkdir -p $home_path
fi
cp -r resources $home_path
$boot_script &
